apiVersion: v1
kind: DeploymentConfig
metadata:
  name: rhe-fe
  labels:
    app: rhe-fe
spec:
  replicas: 2
  selector:
    app: rhe-fe
    deploymentconfig: rhe-fe
  template:
    metadata:
      labels:
        app: rhe-fe
        deploymentconfig: rhe-fe
    spec:
      containers:
        - image: docker-registry.default.svc:5000/rubenmartinez/rhe-fe
          imagePullPolicy: Always
          name: rhe-fe
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - TODO_MS=todo:8081
          - DB_DATASOURCE=jdbc:mysql://mysql-fe/todoapp
