apiVersion: v1
kind: DeploymentConfig
metadata:
  name: mysql-todo
  labels:
    app: mysql-todo
spec:
  replicas: 1
  selector:
    app: mysql-todo
    deploymentconfig: mysql-todo
  template:
    metadata:
      labels:
        app: mysql-todo
        deploymentconfig: mysql-todo
    spec:
      containers:
        - image: docker-registry.default.svc:5000/mysql:5.6
          imagePullPolicy: Always
          name: mysql-todo
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
          - MYSQL_DATABASE=todoapp
          - MYSQL_USER=rhe-todo
          - MYSQL_PASSWORD=rhe-todo
          - MYSQL_RANDOM_ROOT_PASSWORD=yes
